name: Run App

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Quote message from Slack (required)"
        required: true
      quoter:
        description: "Name of the quoter (required)"
        required: true

jobs:
  check-artifact:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      binary_exists: ${{ steps.check.outputs.binary_exists }}
    steps:
      - name: Run citoer
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/${REPO}:latest
          docker run --rm ghcr.io/${REPO}:latest

      - name: Check if binary exists
        id: check
        run: |
          if [ -f citoer ]; then
            echo "binary_exists=true" >> $GITHUB_OUTPUT
            echo "✓ Using cached binary"
          else
            echo "binary_exists=false" >> $GITHUB_OUTPUT
            echo "⚠ Artifact expired or not found. Will rebuild..."
          fi

  build:
    needs: check-artifact
    if: needs.check-artifact.outputs.binary_exists == 'false'
    uses: ./.github/workflows/build.yml

  run:
    needs: [check-artifact, build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Run citoer
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/${REPO}:latest
          docker run --rm ghcr.io/${REPO}:latest

      - name: Make binary executable
        run: chmod +x citoer

      - name: Run app
        run: ./citoer
        env:
          MESSAGE: ${{ github.event.inputs.message }}
          QUOTER: ${{ github.event.inputs.quoter }}

          # Storage option
          STORAGE: "google_sheets" # Make this configurable from github variables

          # Database configurations
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_SHEETS_PAGE_NAME: ${{ vars.GOOGLE_SHEETS_PAGE_NAME }}
          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ vars.GOOGLE_SHEETS_SPREADSHEET_ID }}
